name = input()
cost = int(input())
weight = int(input())
money = int(input())
print("Чек")
print(name, " - ", weight, "кг", " - ", cost, "руб/кг", sep='')
print("Итого: ", cost * weight, "руб", sep='')
print("Внесено: ", money, "руб", sep='')
print("Сдача: ", money - (cost * weight), "руб", sep='')